apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-servicos-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-servicos-frontend
  template:
    metadata:
      labels:
        app: central-servicos-frontend
    spec:
      containers:
        - name: central-servicos-frontend-container
          image: registry.digitalocean.com/oondemand/central-servicos-frontend:1.0.1
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.1"
            limits:
              memory: "2048Mi"
              cpu: "2"