apiVersion: v1
kind: Service
metadata:
  name: central-servicos-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: central-servicos-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000